export const words = [
	'JavaScript',
	'TypeScript',
	'React',
	'Angular',
	'Vue',
	'Svelte',
	'Next.js',
	'NestJS',
	'Node.js',
	'Django',
	'Flask',
	'Spring Boot',
	'ASP.NET',
	'GraphQL',
	'REST API',
	'Microservices',
	'Docker',
	'Kubernetes',
	'CI/CD',
	'WebAssembly',
	'Monorepo',
	'RxJS',
	'Redux',
	'Zustand',
	'Vite',
	'Webpack',
	'Tailwind',
	'Bootstrap',
	'Material UI',
	'MongoDB',
	'PostgreSQL',
	'SQL',
	'NoSQL',
	'Redis',
	'Firebase',
	'OAuth',
	'JWT',
	'Google Pub/Sub',
	'WebSockets',
	'Serverless',
	'Flutter',
	'Swift',
	'Kotlin',
	'Rust',
	'Go',
	'C#',
	'Java',
	'Python',
	'PHP',
	'Laravel',
	'Ruby on Rails',
	'AI',
	'Machine Learning',
	'Deep Learning',
	'NLP',
	'Computer Vision',
	'Generative AI',
	'Transformers',
	'LLM',
	'OpenAI',
	'GPT',
	'BERT',
	'Stable Diffusion',
	'LangChain',
	'TensorFlow',
	'PyTorch',
	'Keras',
	'Hugging Face',
	'Reinforcement Learning',
	'Prompt Engineering',
	'AI Ethics',
	'Explainable AI',
	'AutoML',
	'Edge AI',
	'Federated Learning',
	'GANs',
	'Neural Networks',
	'Data Science',
	'Big Data',
	'Data Mining',
	'Data Engineering',
	'Quantum Computing',
	'Relativity',
	'String Theory',
	'Dark Matter',
	'Astrophysics',
	'Cosmology',
	'Nuclear Physics',
	'Thermodynamics',
	'Particle Physics',
	'Chaos Theory',
	'Cryptography',
	'Algebra',
	'Calculus',
	'Linear Algebra',
	'Topology',
	'Number Theory',
	'Game Theory',
	'Probability',
	'Statistics',
	'Mathematical Modeling',
	'Quantum Entanglement',
	'Nanotechnology',
	'Biophysics',
	'Genome Editing',
	'CRISPR',
	'Synthetic Biology',
	'Astrobiology',
	'Bioinformatics',
	'Cybersecurity',
	'Penetration Testing',
	'Ethical Hacking',
	'Zero Trust',
	'Blockchain',
	'Ethereum',
	'Bitcoin',
	'Smart Contracts',
	'DeFi',
	'NFTs',
	'Metaverse',
	'Cryptography',
	'Digital Identity',
	'Zero Knowledge Proofs',
	'Solidity',
	'Web3',
	'Polkadot',
	'Cardano',
	'Binance Smart Chain',
	'Tokenomics',
	'Layer 2 Solutions',
	'Consensus Algorithms',
	'Wallet Security',
	'Phishing',
	'Ransomware',
	'DDoS',
	'Philosophy',
	'Stoicism',
	'Existentialism',
	'Minimalism',
	'Productivity',
	'Innovation',
	'Design Thinking',
	'Mindfulness',
	'Self-Improvement',
	'Digital Nomad',
	'Remote Work',
	'Future of Work',
	'Metacognition',
	'Neuroscience',
	'Behavioral Economics',
	'AI and Ethics',
	'Psychology',
	'Cognitive Science',
	'Sustainable Development',
	'Climate Change',
	'Space Exploration',
	'Mars Colonization',
	'Longevity',
	'Transhumanism',
	'Philosophy of Mind',
	'Entrepreneurship',
	'Startup Culture',
	'Agile Methodologies',
	'DevOps',
	'Lean Startup',
	'UI/UX Design',
	'Product Management',
	'Digital Transformation',
	'Data Privacy',
	'Ethics in Tech',
	'Cloud Computing',
	'Augmented Reality',
	'Virtual Reality',
	'Internet of Things',
	'Smart Cities',
	'Digital Twins',
	'Biohacking',
	'Immersive Technologies',
	'Edge Computing',
	'Public Health',
	'Epidemiology',
	'Immunology',
	'Virology',
	'Genetics',
	'Bioinformatics',
	'Mental Health',
	'Psychotherapy',
	'Neuroscience',
	'Pharmacology',
	'Telemedicine',
	'Digital Health',
	'Wearable Health Tech',
	'Longevity Science',
	'Anti-aging',
	'Preventive Medicine',
	'Functional Medicine',
	'Nutrigenomics',
	'Sleep Science',
	'Gut Microbiome',
	'Physical Therapy',
	'Orthopedics',
	'Sports Medicine',
	'Cardiology',
	'Cancer Research',
	'Regenerative Medicine',
	'Stem Cell Therapy',
	'CRISPR in Medicine',
	'AI in Healthcare',
	'Robotic Surgery',
	'Health Informatics',
	'Medical Ethics',
	'Healthcare Policy',
	'Alternative Medicine',
	'Holistic Health',
	'Fitness & Nutrition',
	'Mental Wellness',
	'Yoga & Meditation',
	'Weight Management',
	'Physiology',
	'Culinary Arts',
	'Molecular Gastronomy',
	'Michelin Star Chefs',
	'Fusion Cuisine',
	'Vegan Cuisine',
	'Plant-based Diets',
	'Farm-to-Table',
	'Food Science',
	'Nutrition',
	'Fermentation',
	'Sustainable Eating',
	'Food Security',
	'Superfoods',
	'Keto Diet',
	'Paleo Diet',
	'Mediterranean Diet',
	'Wine Tasting',
	'Coffee Culture',
	'Artisan Baking',
	'Pastry & Desserts',
	'Street Food',
	'Food Trends',
	'Ethnic Cuisine',
	'Slow Food Movement',
	'Organic Farming',
	'Agroecology',
	'Food Waste Reduction',
	'Aquaponics',
	'Hydroponics',
	'Gastronomy & Culture',
	'Food Safety',
	'Food Packaging Innovation',
	'GMO Technology',
	'Startup Ecosystem',
	'Venture Capital',
	'Angel Investing',
	'Bootstrapping',
	'Lean Startup',
	'Growth Hacking',
	'Product Market Fit',
	'Business Model Canvas',
	'Agile Leadership',
	'Scrum Methodology',
	'OKRs',
	'KPIs',
	'Corporate Strategy',
	'Digital Transformation',
	'Mergers and Acquisitions',
	'Financial Literacy',
	'Investment Strategies',
	'Stock Market Analysis',
	'Cryptocurrency Investing',
	'Blockchain in Finance',
	'Decentralized Finance (DeFi)',
	'Real Estate Investment',
	'Crowdfunding',
	'E-commerce Strategies',
	'Subscription Models',
	'SaaS Business Models',
	'Branding & Marketing',
	'Sales Funnels',
	'Customer Retention',
	'AI in Business',
	'Data-Driven Decision Making',
	'Business Analytics',
	'Supply Chain Optimization',
	'Sustainable Business',
	'Corporate Social Responsibility (CSR)',
	'Negotiation Skills',
	'Digital Art',
	'NFT Art',
	'Photography',
	'Film Directing',
	'Screenwriting',
	'Graphic Design',
	'Typography',
	'UI/UX Design',
	'Virtual Reality Art',
	'Augmented Reality Art',
	'Video Game Design',
	'3D Modeling',
	'Animation',
	'Storytelling',
	'Creative Writing',
	'Art History',
	'Cultural Anthropology',
	'Music Production',
	'Sound Design',
	'Fashion Design',
	'Architecture',
	'Interior Design',
	'Sculpture',
	'Street Art',
	'Calligraphy',
	'Performance Art',
	'Podcasting',
	'Vlogging',
	'Influencer Marketing',
	'Fan Culture',
	'Cosplay',
	'Memetics',
	'Renewable Energy',
	'Solar Power',
	'Wind Energy',
	'Hydropower',
	'Geothermal Energy',
	'Climate Change',
	'Carbon Neutrality',
	'Sustainable Agriculture',
	'Circular Economy',
	'Waste Management',
	'Green Technology',
	'Eco-Innovation',
	'Sustainable Urban Planning',
	'Biodiversity Conservation',
	'Environmental Policy',
	'Clean Water Access',
	'Ocean Conservation',
	'Deforestation Prevention',
	'Electric Vehicles',
	'Smart Grids',
	'Carbon Offsetting',
	'Plastic Pollution',
	'Eco-tourism',
	'Permaculture',
	'Rewilding',
	'Sustainable Fashion',
	'Climate Finance',
	'Environmental Education',
	'Zero Waste Lifestyle',
	'Game Development',
	'Unity',
	'Unreal Engine',
	'Game AI',
	'Procedural Generation',
	'VR Gaming',
	'AR Gaming',
	'Metaverse Games',
	'eSports',
	'Competitive Gaming',
	'Game Design Theory',
	'Player Psychology',
	'Level Design',
	'Mobile Game Development',
	'Indie Game Development',
	'Gamification',
	'Retro Gaming',
	'Game Streaming',
	'Twitch Communities',
	'Speedrunning',
	'Game Storytelling',
	'NPC Design',
	'VR Training Simulations',
	'AI in Games',
	'Blockchain Gaming',
	'Game Monetization',
	'Cognitive Behavioral Therapy',
	'Positive Psychology',
	'Emotional Intelligence',
	'Habit Formation',
	'Atomic Habits',
	'Time Management',
	'Flow State',
	'Deep Work',
	'Mindfulness Practices',
	'Stoicism',
	'Meditation Techniques',
	'Resilience Building',
	'Personal Growth',
	'Leadership Skills',
	'Decision-Making Strategies',
	'Neuroscience of Habits',
	'Productivity Frameworks',
	'Burnout Prevention',
	'Mental Models',
	'Self-Discipline',
	'Procrastination Hacks',
	'Goal Setting',
	'Visualization Techniques',
	'Public Speaking',
	'Negotiation Tactics',
	'EdTech',
	'Online Learning',
	'Gamified Learning',
	'Microlearning',
	'Learning Analytics',
	'Adaptive Learning',
	'Digital Literacy',
	'Critical Thinking',
	'Project-Based Learning',
	'Flipped Classroom',
	'MOOCs',
	'STEM Education',
	'Coding for Kids',
	'AI in Education',
	'Virtual Classrooms',
	'Lifelong Learning',
	'Soft Skills Development',
	'Educational Psychology',
	'Knowledge Management',
	'Personalized Learning',
	'Digital Nomad Education',
	'Skill-based Education',
	'Peer-to-Peer Learning',
	'Online Communities',
]
